### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kelseyduffy**
added the step of creating an OMF Connection for OCS to the readme

### CODE REVIEW

**Review by derekendres — APPROVED** [review]

**Comment by dcbroad3** [comment]
I suspect that some of the recent sds python sample library changes caused the test for this sample to break. @derekendres do you think Kelsey should try to fix that in this PR or should that be assigned for someone to work on separately? I'm sure that Kelsey's actual changes in this PR are not the cause of the broken build since it is only the README, so we could ignore the failure, merge, and address the build failure separately.

**Review by dcbroad3 — APPROVED** [review]

**Pull request merged**
